build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.20
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: eco-ci-cd
  cluster: build05
  cron: 00 12 * * 1
  steps:
    workflow: telcov10n-slcm
zz_generated_metadata:
  branch: slcm-main
  org: openshift-kni
  repo: eco-ci-cd
